### ISSUE TITLE
Invalid Request

### ISSUE THREAD

**Issue by attawit** [openstudioproject/openstudio#121]
I have tried with the Latest Release 2018.  The following menu 
- Add Schedule/Class
- Add Teacher
- Add  Employee

After click NEXT it show Invalid Request , However, the data have been put into the database. But for Schedule/Class, we have to edit to link with Teacher 
 Thanks you

**Comment by attawit** [comment]
Ok, I found that it is path issue

**Comment by MNXANL** [comment]
Hello, I am having a similar issue. Do you recall how did you solve it?

**Comment by MNXANL** [comment]
Nevermind, it was on 
`next_url = '/customers/add_redirect_on_create?cuID=[id]'`
to
`next_url = '/**openstudio**/customers/add_redirect_on_create?cuID=[id]'`

(assuming the last published version

**Comment by edwinvandeven** [comment]
I recommend hosting OpenStudio on the root of a (sub) domain. Some paths are hardcoded and therefore don't get generated dynamically. 
eg. demo.openstudioproject.com will work, but openstudioproject.com/demo will give some unexpected behavior like you found.
