### ISSUE TITLE
Payment provider 

### ISSUE THREAD

**Issue by mgailitis** [openstudioproject/openstudio#156]
When trying to change payment provider from Mollie to "Don't accept online payments", form waits for Mollie api key. Leaving it empty generates error. If i enter any kind of number, it saves correctly.
![2018-09-26 16_45_50-](https://user-images.githubusercontent.com/12846770/46084314-0fe4f900-c1ac-11e8-9b63-016da6bd046b.png)

**Comment by edwinvandeven** [comment]
Thank you for reporting, this will be fixed in the next release. A release date hasn't been set yet, but expected around the end of October.
