### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by mapo80** [openstudioproject/openstudio#19]
Hi guys,
 I saw your software and I like it. I would like to use it for CrossFit courses. There are all the necessary functions to manage the CrossFit courses. The only feature to completely review is the self checkin, because it is not intuitive and user friendly. Have you planned to develop a mobile application by using something like Ionic framework?

Bye.

**Comment by edwinvandeven** [comment]
Hi,

The self check-in is based around the assumption that customers will have already booked a class in advance using the shop in OpenStudio. Once a customer has booked a class they will show up in the list for that class in the self check-in with a simple "check-in" button next to their name, allowing customers to check-in with a single action. 

A mobile app is not in the pipeline right now, we're very busy adding a point of sale feature... hopefully coming late this year. Though an app might be a meaningful step after that.
