### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'NoneType' and 'long'

### ISSUE THREAD

**Issue by mgailitis** [openstudioproject/openstudio#190]
If user have an unlimited classes in class card, it gets TypeError: unsupported operand type(s) for -: 'NoneType' and 'long'

profile.py line 586
def classcard_get_remaining(row):
    total_classes = row.school_classcards.Classes
    if total_classes == 0:
        remaining = T('Unlimited')

Changed to:
def classcard_get_remaining(row):
    total_classes = row.school_classcards.Classes
    if total_classes in (0, None):
        remaining = T('Unlimited')

Now works as expected.

**Comment by edwinvandeven** [comment]
This is fixed in the upcoming release!

in the mean time, you might want to check like this for more reliable code,

if row.school_classcards.Unlimited:
instead of 
if total_classes == 0:
