### ISSUE TITLE
Incorrect time

### ISSUE THREAD

**Issue by mgailitis** [openstudioproject/openstudio#215]
Server has correct timezone, sql server as well, time zone in OpenStudio correct, but time in class schedule and task scheduler is UTC, not my time zone.
![2018-11-05 17_04_58-systemtime](https://user-images.githubusercontent.com/12846770/48005951-60d9fc80-e11d-11e8-96f6-652c982b8518.png)
![2018-11-05 17_05_23-sysadmin](https://user-images.githubusercontent.com/12846770/48005952-61729300-e11d-11e8-8fe7-d3a70e9e5bbb.png)
![2018-11-05 17_05_45-system settings](https://user-images.githubusercontent.com/12846770/48005953-61729300-e11d-11e8-9aaf-afcc9452425f.png)

**Comment by edwinvandeven** [comment]
OpenStudio assumes the server time and time of scheduled tasks to be UTC to accommodate multiple installations with different timezones on the same server.
