### ISSUE TITLE
Quickstart Onboarding 'Wizard'

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio#296]
It would greatly accelerate deployment and increase the retention rate of new users to OpenStudio if there was a utility that guided the user though the creation of prerequisite records for the successful launch that reduces, minimized or eliminates anomalous operation of the software due to lack of prepopulation.

It would, for example guide a user through the quickstart instructions from start to finish and could even educate the user about the purpose of the records and how to use features of the software as the prerequisite records are being input.  At a minimum, each section of the wizard could have a link to a section of the user manual that the records the wizard is asking for are relevant to.

**Comment by NerdsLogic** [comment]
It would be helpful to know concisely what the minimum prerequisite records are in order to launch the application without encountering errors.  The quickstart guide seems be a checklist of sorts, but suggests inputting information that isn't required.  I've already added a deployment_checklist.rst intended to compile and communicate this information.

**Comment by edwinvandeven** [comment]
Will be tracked in the Costasiella project moving forward.
