### ISSUE TITLE
FILTERED RESULTS ALERT

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio#297]
On pages where you can filter lists using a search box, such as in the Customers List, it may be helpful to prominently display "FILTERED RESULTS" somewhere on the page to remind the user that the may not be complete because the search box has a filter value in it. (is not empty)

A user may become confused that they're unable to locate a record or fear data loss because they are unaware that the list they're looking at is filtered because there are still characters in the search box.

It would be even better if the alert gave you a link/button to click in order to quickly clear the search box and display all results.

**Comment by edwinvandeven** [comment]
From now on this issue will be tracked in the Costasiella project.
