### ISSUE TITLE
Analytics setup page

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio#303]
Support for setting up your google analytics ID - at least for the public store, and perhaps as an option for all or pubic only.

**Comment by NerdsLogic** [comment]
A field for google_analytics_id field might fit nicely into Settings -> System - ?

   `    {{if response.google_analytics_id:}}
    
    <script src="{{=URL('static','js/analytics.min.js')}}"></script>
    <script type="text/javascript">
      analytics.initialize({
      'Google Analytics':{trackingId:'{{=response.google_analytics_id}}'}
      });`

**Comment by edwinvandeven** [comment]
This issue will be tracked in Costasiella from now on.
