### ISSUE TITLE
Option for 12 hour time display format under Settings -> System -> General

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio#304]
United States users will be accustomed to 12 Hour time format in AM / PM

**Comment by edwinvandeven** [comment]
Another good point for the migration to python 3. I would prefer it if the time display is picked up based on the translation file for example, this way localization is a bit more extensive and easier to maintain.

**Comment by edwinvandeven** [comment]
This will be implemented in the "Costasiella" project.
