### ISSUE TITLE
Suggegst changing the Description of the project to include other types of studios

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio#305]
Suggest changing the description of the project from "Open source yoga studio software
" to "Open source yoga / dance studio software" in order to attract more attention to it.

Here is a list of other potential types of organizations / keywords that will benefit from this software:
Cross Training
Spin / Cycling
Karate
Martial Arts
Fitness
Pliates
Circuit Training
Barre
CHILD CARE SPINOFF?
Arial
Silk
Dog Training / Dog Walking
Online scheduling, Payment processing
Kickboxing

**Comment by NerdsLogic** [comment]
Updated ./Readme.md as follows:

OpenStudio is freely distributed open source web based software built for Yoga, Dance, Karate/Martial Arts, and Fitness Studios/Schools. Here just a sample of the types of businesses OpenStudio serves:

- Yoga            - Dance        - Martial Arts
- Cycling / Spin  - Fitness      - Circuit Training
- Pilates         - Barre        - Arial / Silk
- Kick Boxing     - Schools      - Dog Training / Walking

Any organization or business dealing with subscriptions, classes and/or events could benefit from the use of OpenStudio.

OpenStudio will help you manage customers, subscriptions, class cards, schedule classes, plan events, calculate instructor payments, calculate & report revenue and more.

**Comment by edwinvandeven** [comment]
Yes I'm starting to think that even a complete rename of the project might be in place. The word "Studio" in the name might start limiting it in the near future.

**Comment by NerdsLogic** [comment]
If the software was doing something to store the outcomes for the various students in the classes or serious or classes, i would start to call it school management.  In my mind, and without reaching for a consensus, when I think what is the difference between a school and a studio when a studio is also a school...  Well the difference is that studios teach in a practical manner and do not tend to track nor value the same metrics of progress of their students as well in as rigid a manner as does a 'school'  I'll will acknowledge that there are plenty of schools that don't have these requirements or can satisfy them elsewhere and still benefit from this software. 

That being said - this software on its current development course already fits a very large niche very nicely and has tremendous potential to 'HELP A LOT OF PEOPLE'  It can be adapted to be more useful to schools by adding curriculum and outcome handling, matriculation (outcome requirements, prerequisites), and the sort....  My posture at this time is - OpenStudio is a brilliant name for this project.  It already services a niche that is bigger than this project!   Perhaps rebranding a copy of the same software in order appeal to schools vs. studios is a good option.

See the following snippets from industry research available from IBISworld.com where I have selected three studio industries, Dance, Yoga and Marial Arts with combined revenue of 18.4 billion in United States as of 2017:

"Rhythmic movement: Mainstream popularity of dance will continue boosting industry revenue

In 2017, the **DANCE Studios** industry is expected to generate **$3.3 billion in revenue**. This represents annualized revenue growth of 3.5% over the five years to 2017, including expected growth of 1.2% in 2017 alone. The popularization of dance-inspired television shows and rising interest in dance as an alternative form of exercise has positively impacted the industry over the past five years. In particular, dance studios offering Latin-inspired, fitness, fusion and ballroom dance classes have benefited from rising consumer demand. For instance, there was a 30.0% spike in the number of people taking ballroom lessons and attending ballroom events during the first decade of this century, according to USA Dance Inc."

Over the past five years, the **PILATES & YOGA** Studios industry has **grown by 10.6% to reach revenue of $11bn in 2017**. In the same timeframe, the number of businesses has grown by 5.4% and the number of employees has grown by 4.6%.

Over the past five years, the **Martial Arts** Studios industry has **grown by 4.2% to reach revenue of $4bn** in 2018.

**Comment by NerdsLogic** [comment]
Issue has been closed because the recommended changed occurred when README.md was updated and merged.
