### ISSUE TITLE
Implement Facebook login / single sign-on

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio#309]
Facebook Documentation in regards:
https://developers.facebook.com/docs/facebook-login/overview

Web2Py Documentation in regards:
http://www.web2py.com/books/default/chapter/29/09/access-control#Other-login-methods-and-login-forms

**Comment by edwinvandeven** [comment]
Django allauth will be used after the python 3 migration, this library includes many login methods. I'd say this has medium priority, as it's not critical for system operation.
