### ISSUE TITLE
New homepage layout

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio#310]
Upon considering the utility of embedding tracking links it occurred to me that the home page of the application is pretty dry but could potentially be a suitable Home Page website for studio's with simple website requirements., further increasing the utility of this Software Project by giving it the ability to be a complete forward facing website and studio management solution in one.

The SHOP homepage should be more like the employee pinboard with "Get this" buttons  (or whatever drill down button) next to classes, making them offers.  Clicking on the class while anonymous would take you to the class details page and offer you purchase options (subscription, card, drop-in) or sign in for more options.  (sign in required to check offer availability? or notify offers invalid after validating account if not eligible?) 

When visiting the website and not logged in, we should be in the store, instead of /users, because the store should always face the public.  This would a more suitable default landing page with branding and Sign In options along the header.

![newlayoutproposal](https://user-images.githubusercontent.com/29794179/50733581-f9ecba00-1144-11e9-9ce0-c0a04c17364c.JPG)

In the body can display the next classes, special offers and future classes (similar to pinboard).   Additional panes could contain typical website info, promoted events, announcements and Blogs.  As example.  I've created a graphic based on the vision described

 Something like this would make the home page of the application desirable for indexing by search engines and be an effective landing page for search results and other sources of traffic and increase conversions with a live, dynamic and always up to date presentation of operationally driven information.

**Comment by NerdsLogic** [comment]
Since permissions are required to view classes - there will need to be a role for the 'webstore worker' to offer products and promotions to anonymous visitors.

**Comment by edwinvandeven** [comment]
I like the idea, then it would be a good start to have something like "featured" products on the back-end where someone could define what's on the shop home page. 
We'd also need some settings to show what would be on the customer facing landing page, as preferences might change depending on the studio.

**Comment by edwinvandeven** [comment]
In the Costasiella project the shop page has been made the landing page for not signed in users. 
This creates a good starting point for greater engagement for non signed in users. 

Further improvement of the shop home page is tracked in the costasiella issue mentioned above.
