### ISSUE TITLE
New Class Record can be orphaned

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio#314]
When creating a class that who's Start and End dates do not include the day of the week that is configured in the Weekday field will no display in the schedule after being saved.  This will cause the class to effectively become orphaned from the user interface :(

You will have to use the clsID number of the class in the URL of  /classes/class_edit?clsID={clsID} in order to access and modify the interface orphaned record.  

A possible solution is to prevent records as such from being validating that at least one of the day selected exist in the date range configured, alerting to the validation error and abort post.

**Comment by edwinvandeven** [comment]
This has been solved in the Costasiella project. The user now has the choice of single or recurring classes. For a recurring class the dates need to be at least 7 days apart, to prevent the class not showing up in the user interface after creation.
