### ISSUE TITLE
Can not enroll student in class with Classcard group that allows booking (enrollment)

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio#322]
While attempting to enroll a student into a class, their eligible class card (class card group allows booking) doesn't show up when trying to add a class booking from the booking tab of a class.  I'm able to start the booking but on the page where a class card should be selected, there are no options.  (enrollment can happen with class cards, right?)

**Comment by edwinvandeven** [comment]
Enrollments on classcards are currently not supported in the same way as with subscriptions. For a subscription the classes are booked when credits are given from the automation menu. As this is not possible for a card, customers get an option to make a recurring booking until either the book in advance limit set in OpenStudio or the card runs out of classes. 
Though there's currently no way to do this from the back-end. Only customers can do this during the booking process.
