### ISSUE TITLE
Shop>Workflow - Classes advance booking limit in days fails on validate of clean field

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio#323]
/shop_manage/workflow#
When saving the form Shop>Workflow - The "Classes advance booking limit in days" field will fail validation when left blank even though this value has not been set before and is not being edited now.

Consider allowing a null value and validating input if dirty?  and perhaps null = no limit, 0 = no cancellations

**Comment by edwinvandeven** [comment]
In the Costasiella project a default value has been set to prevent this issue.
