### ISSUE TITLE
Prompt for save on dirty tabs

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio#335]
When making changes on the tabs of many types of records, you could make changes in one tab and then change to another tab to make additional changes.  When clicking on Save after making changes on the second tab, the field changes in the first tab are not saved.  (Right now the user must click Save before switching tabs in order to commit the changes)

I suggest adding some sort of IS DIRTY? validation before switching tabs to prevent people like me from thinking they've commit information to memory but have instead lost it to cyberspace.

**Comment by edwinvandeven** [comment]
This would definitely be useful. I'd like schedule it as an overall usability improvement after porting to python 3

**Comment by edwinvandeven** [comment]
From now on this issue will be tracked in the Costasiella project.
