### ISSUE TITLE
Payment method Field

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio#337]
When paying an invoice for a classcard, for example, making a payment against the invoice with the payment method of cash does not mark the invoice as paid by method Cash.  Consequently when the class card shows up in the customers Class Card Tab, the payment method column is blank unless you manually set the payment method in the invoice.

What is the purpose of this field?  Is it supposed to be set during payment?

**Comment by edwinvandeven** [comment]
This field is used to specify whether an invoice should be paid using direct debit. In most cases it's empty/unused.
The actual payment for an invoice will always have a payment method.
