### ISSUE TITLE
Class Check-In Booking Options - Rows of options are ambiguous on wide display

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio#338]
Below is a snip of the booking options page when signing a student into class.  The rows are somewhat difficult to follow on a wide display.

![image](https://user-images.githubusercontent.com/29794179/51089779-dcf94d80-1727-11e9-9d17-1b5e1d1d9883.png)

Below is an example of a solution to assist with visually following the row of available check-in options.  Please see the background shading of alternate rows formatting in the image below from the Customer>Classes Tab

![image](https://user-images.githubusercontent.com/29794179/51089762-78d68980-1727-11e9-8369-5e432705ad01.png)

**Comment by edwinvandeven** [comment]
Solved in Costasiella by displaying the booking options as cards instead of rows
