### ISSUE TITLE
Able to double book a class from Customers>Classes>Add if you double click the Check-In button

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio#339]
Able to double book a class from Customers>Classes>Add if you double click the check-in button.

An unsuspecting user could do this accidentally or habitually and double deduct classes from somebodies account.

**Comment by edwinvandeven** [comment]
Sounds like the check-in button should deactivate using javascript after the first click. There is a check in the back-end to prevent duplicate entries, but it doesn't work for fast consecutive clicks, as there's no record in the database yet.

**Comment by edwinvandeven** [comment]
Implemented in the costasiella project. All buttons disable as soon as clicked and while waiting for the backend to process.
