### ISSUE TITLE
Unable to enroll student into class with classcard - no options to enroll

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio#340]
With a class that has 1 enrollment space, I'm unable to enroll a student into the class - no enrollment options are displayed when selecting the student that I want to enroll.
![image](https://user-images.githubusercontent.com/29794179/51156990-d73c5e80-1832-11e9-9d79-b9fd896dc99a.png)

After clicking Add, No options displayed for student...  see below :(
![image](https://user-images.githubusercontent.com/29794179/51157035-faffa480-1832-11e9-9039-e15935357569.png)

**Comment by edwinvandeven** [comment]
Yes, this is by design. It's not possible to enroll students from the back-end using a card. Only subscriptions can be used for enrollments. The only workaround that's technically possible would be to offer an option to book multiple classes until the card runs out of classes.

**Comment by NerdsLogic** [comment]
For purposes of documentation, feature clarification/modification purposes - lets discuss Enrollments.  It seems that enrollments were written to be used in parity with subscriptions, however, in the absence of documentation it seems like enrollment is the act of "reserving" or marking in advance your attendance to a class and _a class card holder may like to reserve their spot in an upcoming class in advance._  In these cases this could be perceived as a bug and not a limitation by design.

In order to address this confusion lets discuss and update the documents - What are enrollments to OpenStudio?

**Comment by edwinvandeven** [comment]
Will be tracked in Costasiella

Backend
https://github.com/costasiella/costasiella/issues/255

Docs
https://github.com/costasiella/costasiella_docs/issues/10
