### ISSUE TITLE
Unauthorized cannot see classcards or subscriptions

### ISSUE THREAD

**Issue by mgailitis** [openstudioproject/openstudio#347]
After upgrade to v.2019.01.1, i got error on listing classcards or subscriptions if i'm not authorized.
Error message:
<type 'exceptions.AttributeError'>('NoneType' object has no attribute 'id')

**Function argument list**
(self=<applications.openstudio.modules.openstudio.os_school.School instance>, scdID=14L, school_memberships_id=None, customer_has_membership=False)

**Comment by edwinvandeven** [comment]
This is a duplicate of #341 
Will be fixed in the upcoming release.
