### ISSUE TITLE
Unable to click Edit button on line item of invoice from Mobile

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio#360]
Unable to click Edit button on line item of invoice.  Using Google Chrome browser on Android  8.0 mobile device.

![image](https://user-images.githubusercontent.com/29794179/52080965-e703b480-254d-11e9-9c38-9015528419fe.png)

**Comment by edwinvandeven** [comment]
Closed as OpenStudio is nearing the end of it's life cycle and it's usable on a desktop/laptop.
