### ISSUE TITLE
Invoices to e-mail

### ISSUE THREAD

**Issue by mgailitis** [openstudioproject/openstudio#366]
I've been using openstudio for a while in our CrossFit box and clients asked if it is possible to get subscription and class card invoices or information about created invoice to their registered e-mail address as soon as invoices are created? Do you plan to implement such an automatic invoice sending feature - i think that would be really usefull!

**Comment by edwinvandeven** [comment]
I agree, it would definitely be a very useful feature. Though at the moment almost all work goes into making a python 3 port using modern technologies like GraphQL, so I'm only adding new features to OpenStudio for paying customers at the moment, though I'll leave this issue open and I'll add it at some point once the port to python 3 is finished.

**Comment by edwinvandeven** [comment]
From now this issue will be tracked in the Costasiella project
https://github.com/costasiella/costasiella/issues/256
