### ISSUE TITLE
Roadmap Meeting

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio#367]
### Interface Improvements:
 - Touch Friendly Interface

 - Visual distinction  / Contrasting Rows / Touch sized controls

 - 12 hr / 24 hr Time Display - The typical american end user understands AM/PM format better.  24hr time requires mental jogging to interpret.

### Reporting Improvements: 
 - Calculate Payouts for instructors, Accounts Receivable, Specify dates for reporting period

 - Status Flags that alert operator that a student needs to be prompted for payment/paperwork/task.  For example, when checking in a student, a dollar sign could appear next to their name to indicate they need to be prompted to pay, or to enforce a hold/suspension/denial of service

### General Improvements:
 - Multi Salon per location - (room, studio, classroom, space, partition, etc...)

- Multi-Tennant version for hosting

 - Calendar Syncronization (google, iCal, Outlook/Exchange) - View Schedule by Salon / Location / Organization

 - When creating classes - ability to select one or more days for the class to occur?  (I only have a hunch that this is desirable or useful... or anticipate a demand for this)

 - Additional Payment Integrations - Paypal Directly? - Square - Venmo

 - Bring a Friend check-ins - ?  - Although most studios have a policy against sharing class cards, some studios welcome this and sometimes Students bring friends/family/guests or simply want to comp a classmate charge their own class cards for the other person(s)

 - Bundling Products for purchase - Example - New Student Special $149.95, contains 2 Private Lessons (class card of 2 privates) and 2 Group Classes (Class Card of 2 Group Classes).

### Data Integrity & Validation Improvements:
 - When creating classes, validate day of week selected occurs within the date range specified for the class.

 - When editing information on entity that has multiple tabs, you can loose information if you do not click Save before navigating to another tab because the user may assume or overlook how and when information that has been input is committed to record.

**Comment by edwinvandeven** [comment]
### Transactional emails
Option to mail customers when actions happen

- Subscription added
- Classcard added 
- Class reminders for drop-in and trial classes
- Invoice created (simple link to profile would suffice)

**Comment by edwinvandeven** [comment]
### Studio rental

- Easily check room availability
- Create invoices linked to rentals
- Future: Online bookings of room rentals?

**Comment by edwinvandeven** [comment]
### Invoices

- Public invoices, B2B invoices accessible using uuid url + access code in email. 
- Public B2B invoices payment link to redirect to payment provider

**Comment by edwinvandeven** [comment]
### Private classes

- Teacher / Room availability
- Online booking system for customers
- Invoicing for customers

**Comment by edwinvandeven** [comment]
### Modern technologies

- Back-end: Move to Django (using python3) + GraphQL
- Front-end: React + Appolo GraphQL Client
