### ISSUE TITLE
<type 'exceptions.UnicodeDecodeError'> 'ascii' codec can't decode byte 0xc4 in position 5: ordinal not in range(128)

### ISSUE THREAD

**Issue by mgailitis** [openstudioproject/openstudio#368]
In events section tried to copy an activity and got this error. The same when pushed "Mail attendance list to teacher" in Activities section.
<type 'exceptions.UnicodeDecodeError'> 'ascii' codec can't decode byte 0xc4 in position 5: ordinal not in range(128)
message += unicode(H3(title))
We use šāļķīņč in Latvian language :)

**Comment by edwinvandeven** [comment]
Someone else also encountered this issue and it should be fixed in the next release which is scheduled for early March.
