### ISSUE TITLE
Trial class in self-checkin

### ISSUE THREAD

**Issue by mgailitis** [openstudioproject/openstudio#373]
I have configured classes with Trial pricing absolutely empty (there is no option to get a trial class), but in self-checkin screen i can see this Trial with price 0.00 available. How to disable this?

**Comment by edwinvandeven** [comment]
Currently this option is not yet available, the trial class option is always enabled. It will be included in the upcoming update which is expected before the end of the month

**Comment by edwinvandeven** [comment]
It can be disabled now under settings -> system -> workflow by removing the check in front of "Enable trial class booking option"

**Comment by mgailitis** [comment]
Thanks - perfect :)
