### ISSUE TITLE
Can not buy Drop In class

### ISSUE THREAD

**Issue by mgailitis** [openstudioproject/openstudio#405]
Strange behavior of OpenStudio 2019.04.1. After upgrade i can not book Drop In class.
Find the class, can see the section Drop in, pushing Book, got to the order summary and than pushing Book class. It skips the payment part and goes directly to Complete and i can see that booking became Trial (Trial disabled in Settings-->System-->Workflow) without any payment.
Can make a screenshots, if necessary!

**Comment by edwinvandeven** [comment]
Thanks for reporting, I think I found it. Could you check if 2019.05.1 fixes it?

**Comment by mgailitis** [comment]
Hi!
Ok, i will install update and inform you if it fixes this bug.

**Comment by mgailitis** [comment]
Fixed!
