### ISSUE TITLE
Created classes do not appear in shop

### ISSUE THREAD

**Issue by Lagler** [openstudioproject/openstudio#446]
After setting up openstudio-project I followed all instructions for preliminary configuration (teachers, class types, locations and much more what I believed could fix my problem. (classes not visible)

All created classes do not appear in the shop. (Shop -> Classes). The classes are marked as public. There is no difference if I login as customer or administrator, the classes-shop is empty. In the admin-backend the classes are in the schedule.  
However, created subscriptions are available in the shop.

I would be grateful if someone knows what I was probably misconfiguring or if there is something I should have set. 

Further, we could update the guidelines when we found out the reason what causes the problem.

**Comment by digital-cinema-arts** [comment]
After creating class types they are then added to the class schedule (Schedule->Classes) to be able to show up in the shop.  Have you added classes to the class schedule?

**Comment by digital-cinema-arts** [comment]
Sorry, I missed this:
"In the admin-backend the classes are in the schedule."

Are your School->Locations for the classes public?

**Comment by edwinvandeven** [comment]
For classes to show up in the schedule, the locations and class types also need to be marked as "public" under school. This is to quickly allow setting all classes in a location or type as private, if ever so desired.

Hope this helps!

**Comment by Lagler** [comment]
Many thanks, after marking the location as public the problem was solved!
