### ISSUE TITLE
Logo on default invoice form

### ISSUE THREAD

**Issue by mgailitis** [openstudioproject/openstudio#452]
Hi!
Could you please explain why there is no logo on default invoice form?
In default.html i can see this:
`<body>
    <div class="right studio-info text-right">
        {{=logo}}<br>
        <div class='text-right grey'>
            <span class='bold'>{{=studio['name'].upper()}}</span><br>`

In branding section logos are uploaded!
Thanks in advance!

**Comment by edwinvandeven** [comment]
As I haven't been able to reproduce this issue, I'll close it. 
When a logo has been uploaded, it should show.
