### ISSUE TITLE
Fully booked class - cannot check in

### ISSUE THREAD

**Issue by mgailitis** [openstudioproject/openstudio#480]
Hi!
I have an interesting situation.
Class with 15 students. 15 online booking spaces.  Before the class there were 13 online booked spaces. 20 min before the class, came 2 more students, that did an checkin at the desk where Self Check in screen is opened.
After that all 15 spaces were taken and all others, that have booked the class and arrived after those two, could not push Check-In button. Is that how it should be, or there is some kind of bug?

**Comment by edwinvandeven** [comment]
Hi, this issue should no longer occur in the latest version as it only counts the status "attending" to determine if a class is full or not in the self checkin.
