### ISSUE TITLE
Different price for first payment

### ISSUE THREAD

**Issue by 44db** [openstudioproject/openstudio#515]
Hello, when a subscription is bought a lower price is shown a first payment: https://prnt.sc/uc6l6p
However I have not set a subscription fee.
Why is that?
thanks

**Comment by edwinvandeven** [comment]
Hello!

The billing of subscriptions is based on a monthly cycle, from the first day of the month to the last. When a new subscription is started or a subscription is ended in the middle of a month, the number of billable days for that subscription are calculated, instead of billing a full period.
