### ISSUE TITLE
When adding class, next step redirects to wrong url

### ISSUE THREAD

**Issue by 44db** [openstudioproject/openstudio#516]
Hello,

When adding a class and clicking to next it redirects to a wrong url.
For example:
Original URL: 
https://mydomain.com/openstudio/classes/class_add
Redirected URL after clicking next:
https://mydomain.com/classes/class_teacher_add/?clsID=18&wiz=True

As you can see it is missing the "openstudio" part.
Same happens when adding holiday.

Looks like whenever there is a next step it does that.

Thanks!

**Comment by edwinvandeven** [comment]
Hi,

Please refer to this part in the installation manual:

Starting from version 2.07 Javascript (AJAJ) is used more to make the interface more user friendly. However to make it work, you should use a routes.py file in your web2py root folder to be able to run openstudio from an url like “http://demo.openstudioproject.com”. The url shouldn’t have the app name in it, a url like “http://localhost:8000/openstudio” will cause problems. 

https://openstudio-docs.readthedocs.io/en/latest/installation.html
