### ISSUE TITLE
Invalid controller (user/login) when clicking sign in from shop

### ISSUE THREAD

**Issue by 44db** [openstudioproject/openstudio#517]
Hello,

When clicking Sign In from Shop (without being logged obviously) 
example url: https://mydomain.com/openstudio/shop
it redirects to this urls: https://mydomain.com/openstudio/user/login
and outputs: invalid controller (user/login)

Thanks!

**Comment by edwinvandeven** [comment]
Hi,

Please refer to this part in the installation manual:

Starting from version 2.07 Javascript (AJAJ) is used more to make the interface more user friendly. However to make it work, you should use a routes.py file in your web2py root folder to be able to run openstudio from an url like “http://demo.openstudioproject.com”. The url shouldn’t have the app name in it, a url like “http://localhost:8000/openstudio” will cause problems. 

https://openstudio-docs.readthedocs.io/en/latest/installation.html
