### ISSUE TITLE
Task menu- user filter can't be reset after refreshing the page 

### ISSUE THREAD

**Issue by Shiva-Bot-Py** [openstudioproject/openstudio#522]
After login as a admin, filtered out the task by employee. If i refresh the same page, task field can't be reset (again showing the same name).
What are the possibilities to be select the filter on refresh or navigating to another menu. 

![Screenshot_2020-10-20 Tasks](https://user-images.githubusercontent.com/73157103/96566709-88fb9f80-12e3-11eb-970c-00670793b5df.png)

**Comment by edwinvandeven** [comment]
To be honest, I'm not sure what would be the best way for you. It's using a session variable. You'd have to modify the code to not use it. However, I like the current way it works so I don't want to change this behavior.
