### ISSUE TITLE
Changes are not reflecting in POS Nav bar

### ISSUE THREAD

**Issue by Shiva-Bot-Py** [openstudioproject/openstudio#523]
if i trying to make a changes on POS NAV bar. The changes are not reflecting.

example : if i change menu name "Customer" instead of "Students" . The changes are not reflecting.

**Comment by edwinvandeven** [comment]
Correct, the POS is a separate part of the application built in react. In the app root/react_frontend_src/pos/src you van find the source for the react app. Once you've made the changed you require, run "npm run build" in app root/react_frontend_src/pos.

Make sure you have a working npm / dev setup for this.
