### ISSUE TITLE
Class booking status finished and in progress incorrect

### ISSUE THREAD

**Issue by vpant** [openstudioproject/openstudio#524]
The correct timezone is set in the Settings and the server is configured to the correct timezone as well. Although there is a problem with these statuses. My students can see that a lesson is In progress prior 2 hours of it even start.

Is this a configuration issue? I cannot set the time two hours ahead because then the time of the class our students will see will not be the right one.

**Comment by edwinvandeven** [comment]
Please ensure the server is set to UTC. The application will set the correct timezone based on the UTC server time.
