### ISSUE TITLE
OpenStudio is not Working

### ISSUE THREAD

**Issue by psp316r** [openstudioproject/openstudio#528]
Followed each and every instruction as per the Installation documentation, after running all the commands and solving the errors, now there are no errors, but when I click on the **openstduio** in browser it Shows:
**Internal error**
Ticket issued: unknown
**The output of my terminal:**

```
ubuntu@ip-172-31-38-36:/home/www-data/web2py$ sudo python3 web2py.py
web2py Web Framework
Created by Massimo Di Pierro, Copyright 2007-2020
Version 2.20.4-stable+timestamp.2020.05.03.05.18.50
Database drivers available: sqlite3, psycopg2, imaplib, pymysql
please visit:
        http://127.0.0.1:8000/
starting browser...
starting scheduler from widget for "openstudio"...
Currently running 1 scheduler processes
Processes started
/home/www-data/web2py/gluon/contrib/pymysql/cursors.py:166: Warning: (3090, "Changing sql mode 'NO_AUTO_CREATE_USER' is deprecated. It will be removed in a future release.")
  result = self._query(query)```

**Comment by stevesanda** [comment]
Have you tried running web2py with an assigned interface? I have to type in my web server's IP (`10.0.51.10`) in order to access it outside of localhost.

`python3 web2py.py -a firstpassword -i 10.0.51.10 &`

**Comment by psp316r** [comment]
Yeah, I have solved it, Thanks !!
