### ISSUE TITLE
Delete payment for Invoice

### ISSUE THREAD

**Issue by Shiva-Bot-Py** [openstudioproject/openstudio#529]
When i try to delete the payment for Invoice ..it shows Cancel or OK.

Payment information deleted even i selected the Cancel Option. 
![Screenshot from 2020-11-03 11-56-38](https://user-images.githubusercontent.com/73157103/97955394-14892c00-1dcc-11eb-9148-a52c2d1e98d2.png)

**Comment by edwinvandeven** [comment]
As OpenStudio is reaching the end of it's life a fix won't be implemented anymore.
