### ISSUE TITLE
Unable to send email

### ISSUE THREAD

**Issue by stevesanda** [openstudioproject/openstudio#533]
Hello!

I'm trying to get email working -- I've tried two different SMTP servers (fastmail and gmail) but can't seem to get emails sent. I am testing by hitting "lost password" on the login screen. The error message is "Unable to send email". Are there other logs I can dig up to see what the issue might be?

````
; smtp address and credentials
[smtp]
server = smtp.gmail.com:587
sender = Studio Name <email@gmail.com> ;
 login  = email@gmail.com:apppassword
 tls    = true
 ssl    = true
````

**Comment by mattharris** [comment]
@stevesanda Not sure if you've solved this yet, but I have gotten this to work with Gmail using the following:

 ```
; smtp address and credentials
[smtp]
server = smtp.gmail.com:587
sender = Name <account@example.com>
login  = account@example.com:apppassword
tls    = true
ssl    = false
```
The account has 2-factor authentication enabled with a generated app password.

Like you, I tested using the 'lost password' functionality.
