### ISSUE TITLE
Include customer custom fields

### ISSUE THREAD

**Issue by MaddieBytes** [openstudioproject/openstudio#573]
Would it be possible to include custom fields for users. I am looking at implementing this for a dance studio which will commonly have follows and leads.

If possible the preferred workflow would be:

- User Registration
  - Select lead / follow
- Teacher view class info
  - # of leads and follows in the class

**Comment by edwinvandeven** [comment]
This sounds like a useful feature for dance studio's, but I'm not sure how to implement this technically. Allow me to give some context; OpenStudio will soon go into maintenance mode as development is mainly focused on Costasiella now (https://github.com/costasiella). A project to re-implement the most used features in OpenStudio using more modern frameworks & technologies. Although not production ready right now, a first release is expected before the end of the year.
Any custom work done in OpenStudio would not have a very long life, so I'm not sure if it's wise to implement it at this time. Perhaps the Costasiella project makes the implementation last longer. 

Then about the general implementation; I'm not completely sure what would be the best way. I can't really included it in this form as a feature in the main branch, as it's specific to certain dance studio's only. It wouldn't apply to say a Yoga studio. 

Perhaps a more general way would be to implement tags for user accounts and allowing teachers to view those tags and perhaps have a setting to allow customers to select a tag after registration in case that feature is enabled in customer profiles. 
This could then also be used in the customers list in a more general way to tag someone as a VIP for example. 
It'd be an additional step after registration, but would keep the registration process more relevant to all types of organizations. 

Another route to take might be to have custom fields for users that can show up anywhere, but technically that would take some designing within the Costasiella project. It wouldn't make sense to implement this in OpenStudio anymore. The back-end would need some way to let the front-end know how many and how custom fields should be displayed to users and which data types are expected. Not impossible, but quite a project in it's own right.

Well, these are just some ideas, in case you have another idea that would result in a workflow that can be generally be applied, please let me know.
