### ISSUE TITLE
Please add more data to the demo installation

### ISSUE THREAD

**Issue by labeldevops** [openstudioproject/openstudio#574]
It is very fine that you are offering a demo installation - however, many menu items only show me empty pages, what makes no sense at all. Please add some fake data for at least two years of studio courses going on and some more teachers / scholars etc. so we can see how the system behaves under realistic data load. You might do that with the [Faker](https://pypi.org/project/Faker/) library.

BTW thank you very much for open sourcing this very interesting project!

**Comment by edwinvandeven** [comment]
OpenStudio is nearing the end of it's life, the demo will be kept online for a little longer, but no further work will be put into it.
