### ISSUE TITLE
Scheduler as webdac or ics calendar

### ISSUE THREAD

**Issue by labeldevops** [openstudioproject/openstudio#576]
I see you implemented some mind of schedule / calendar - this is very nice, however it would be great if the calendar could be exported / imported to already existing calendaring infrastructure like e.g. webdav servers or exported to ics files or even interact with hosted calendars like e.g. google calendar or several other implementations of that same thing.

**Comment by labeldevops** [comment]
BTW one good reason t ouse Django is the many projects you can rely on that solved problems already:
https://djangopackages.org/grids/g/calendar/

**Comment by edwinvandeven** [comment]
A while ago some dependencies from another project accidentally made it into OpenStudio's requirements.txt. This has since been rectified. OpenStudio isn't based on Django and django modules aren't compatible. 

As OpenStudio is nearing the end of it's life, this feature won't be implemented.
